### ISSUE TITLE
Update data

### ISSUE THREAD

**Issue by encarsia** [getnikola/nikola-users#10]
Hey,

browsing through the page I stumbled across some vanished pages. Based on the script on the "Check a site" page it came to my mind to just check all entries. Turns out that some sites are gone, some only changed a path/folder and some moved to other generators.
I haven't checked all of these yet but I dumped the output into a JSON file ([nikola_users.json](https://gist.github.com/encarsia/78268dfd79594ea1ca3ab1247c0e0ca3)).¹

Is there a smart way to contribute an updated entry list here?

Cheers

¹ In case you ask what *"Probably a Nikola site"* means: I just searched the index page for the word "Nikola" when searching the rss.xml failed so there could also be some false positives.

**Comment by Kwpolska** [comment]
Hello.

First off, thanks for doing this.  Second, this can only be fixed by me, as only I have access to that site’s admin panel.

Current progress:

* 3 “not sites” are in fact Nikola sites (one had a slightly broken link, I fixed that)
* 33 “not sites” are gone
* 7 “suspicious” sites (with errors) are valid Nikola sites
* 3 “suspicious” sites are gone
* 17 “suspicious” sites with errors are hidden and will be removed in 48 hours if they do not become active again

**Comment by Kwpolska** [comment]
PS. to make this easier for people in the feature, I added a downloads list: https://users.getnikola.com/downloads/

**Comment by encarsia** [comment]
Thanks for your fast reaction and the files for playing around with in dark winter evenings. :D

**Comment by Kwpolska** [comment]
18 more sites were removed.
